[env]
default = "main"

[env.profiles.main]
host = "main"
tunnel = "primary"
scheme = "http"

[launchers]
default-proxy = "main"

[launchers.browsers.entries.chrome]
detect = "chrome"
icon = "GC"

[launchers.applications.entries.editor]
name = "Code"
command = "code"
icon = "VS"

[hosts.main]
ssh-config-host = "localhost"

[[hosts.main.local-proxies]]
name = "primary"
listen = "127.0.0.1:17890"
mixed = true
